version: "3.5"

services:
  jekyll-text-theme_build:
    image: docker_jekyll-text-theme_dev
    environment:
      - JEKYLL_ENV
    container_name: jekyll-text-theme_build
    volumes:
      - ..:/usr/src/app
    command: bundle exec jekyll build
